name: WakaTime

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
